wildfly_home: "/opt/wildfly-11.0.0.Final"
wildfly_url: "http://download.jboss.org/wildfly/11.0.0.Final/wildfly-11.0.0.Final.tar.gz"
wildfly_archive: "/opt/wildfly-11.0.0.Final.tar.gz"
wildfly_install_dir: "/opt"

